INSERT INTO users (name) 
VALUES ('Joe Bloggs'), 
('John Doe'), 
('Jane Smith');

INSERT INTO provinces (full_name, short_name)
VALUES ('Ontario', 'ON'), 
('Quebec', 'QC'),
('Nova Scotia', 'NS'),
('New Brunswick', 'NB'),
('Manitoba', 'MB'),
('British Columbia', 'BC'),
('Prince Edward Island', 'PE'),
('Saskatchwan', 'SK'),
('Alberta', 'AB'),
('Newfoundland and Labrador', 'NL'), 
('Northwest Territories', 'NT'), 
('Yukon', 'YT'), 
('Nunavut', 'NU');

INSERT INTO destinations (name, wiki_name, google_place_id)
VALUES ('Jasper', 'Jasper', 'ChIJKT5VaAgrg1MRgigZC70CIB8'), 
('Banff', 'Banff, Alberta', 'ChIJ_UoMkUXKcFMRY5Ss2r6ur8o'), 
('Vancouver', 'Vancouver', 'ChIJs0-pQ_FzhlQRi_OBm-qWkbs'), 
('Lake Louise', 'Lake Louise, Alberta', 'ChIJEc7hoChdd1MR5rxlY3s8Nzw'), 
('Toronto', 'Toronto', 'ChIJpTvG15DL1IkRd8S0KlBVNTI'), 
('Montreal', 'Montreal', 'ChIJDbdkHFQayUwR7-8fITgxTmU'), 
('Revelstoke', 'Revelstoke, British Columbia', 'ChIJpd1q-gU3eVMRyu_WuX1kPE8'), 
('Haida Gwaii', 'Haida Gwaii', 'ChIJAzMGVmJvbFQR673y7geLkuw'), 
('Quebec City', 'Quebec City', 'ChIJk4jbBYqWuEwRAzro8GMtxY8'), 
('Louisbourg', 'Louisbourg', 'ChIJbSHDjFQdaEsR3aRei1h4IVQ'), 
('Whistler', 'Whistler, British Columbia', 'ChIJh3uVA7I8h1QR9s_1dehBt0o'), 
('Ottawa', 'Ottawa', 'ChIJrxNRX7IFzkwR7RXdMeFRaoo'), 
('Calgary', 'Calgary', 'ChIJ1T-EnwNwcVMROrZStrE7bSY'),
('Victoria', 'Victoria, British Columbia', 'ChIJcWGw3Ytzj1QR7Ui7HnTz6Dg'), 
('Niagara Falls', 'Niagara Falls, Ontario', 'ChIJuU2C7F5E04kRiKK9VmHF0kY'), 
('Halifax', 'Halifax, Nova Scotia', 'ChIJwfrbBxQhWksR3C2LQ6bja2Y'), 
('Winnipeg', 'Winnipeg', 'ChIJESsa-ftz6lIRZMq5xvoaKis'), 
('Kelowna', 'Kelowna', 'ChIJszDH47aMfVMR98S02j3l-E4'), 
('St. John''s', 'St. John''s, Newfoundland and Labrador', 'ChIJYaIKa46jDEsRHyYSHwDUH54'),
('Kingston', 'Kingston, Ontario', 'ChIJqY5AdAar0kwR6tnWFXdJpXY'),
('Mont-Tremblant', 'Mont-Tremblant', 'ChIJF1KUvA12z0wRwFRNrq0MBAU'),
('Hamilton', 'Hamilton, Ontario', 'ChIJj3feJ2yYLIgRIQ7f2Fbuais'), 
('Niagara-on-the-Lake', 'Niagara-on-the-Lake', 'ChIJsQIX2RRf04kRwKIRfVRRAXY'), 
('Saskatoon', 'Saskatoon', 'ChIJK5ntR7_2BFMRkCZ3lTKeBAU'), 
('London', 'London, Ontario', 'ChIJC5uNqA7yLogRlWsFmmnXxyg'), 
('Vancouver Island', 'Vancouver Island', 'ChIJD9RbwiQYiFQRtWoKQiKWmVI'),
('Algonquin Provincial Park', 'Algonquin Provincial Park', 'ChIJ_21BPMh51kwR62D0aOu7bUM'), 
('Nanaimo', 'Nanaimo', 'ChIJWxysIF6hiFQR0A97KhU1AQU'), 
('Kamloops', 'Kamloops', 'ChIJMTsNPdMsflMR50VpmqqWPtI'),
('Jasper National Park Of Canada', 'Jasper National Park', 'ChIJG4dCkcspg1MRktGbzm1KcuE'),
('Mississauga', 'Mississauga', 'ChIJtwVr559GK4gR22ZZ175sFAM'),
('Whitehorse', 'Whitehorse', 'ChIJgVO8gJhEVFERSzXQZOq3PeQ'),
('Big White Ski Resort', 'Big White Ski Resort', 'ChIJNVeBt_-efVMRzAA5aCq3VRY'),
('Canmore', 'Canmore, Alberta', 'ChIJMWNFlZXFcFMRLmkenl8xtkY'),
('Windsor', 'Windsor, Ontario', 'ChIJa4hPtcEqO4gRUdz8J5XUbLY'),
('Regina', 'Regina, Saskatchewan', 'ChIJ6z2l-0AeHFMRsVR7t5YySjU'),
('Yoho National Park Of Canada', 'Yoho National Park', 'ChIJUxBJITveeVMRdW-P2NvpnPI'),
('Squamish', 'Squamish, British Columbia', 'ChIJcy14rBX4hlQR2xFaSWhoqa8'),
('Charlottetown', 'Charlottetown', 'ChIJxYN_1N1SXksRJ5tRn7h3V1o'),
('Yellowknife', 'Yellowknife', 'ChIJyYJGoyzx0VMRge9xQyQ3wbQ'),
('Kitchener', 'Kitchener, Ontario', 'ChIJBVHuA4z0K4gRS1Rf3-b4JZU'),
('Gros Morne National Park Of Canada', 'Gros Morne National Park', 'ChIJ72vPHCBFeUsRdjmRPWNqdWU'),
('Glacier National Park of Canada', 'Glacier National Park (Canada)', 'ChIJxWd-JkUIeVMRuQ7amxSgRPA'),
('Athabasca Glacier', 'Athabasca Glacier', 'ChIJVaomLeX-d1MRZ9IZJSjcXTw'),
('Nahanni National Park Reserve of Canada', 'Nahanni National Park Reserve', 'ChIJybuQCDo94VMRoDoXiK4h0J4'),
('Drumheller', 'Drumheller', 'ChIJHx_0B4ANc1MRWZCRwItZUUw');

INSERT INTO province_destinations (province_id, destination_id)
VALUES (9, 1), 
(9, 2), 
(6, 3), 
(9, 4), 
(1, 5), 
(2, 6), 
(6, 7), 
(6, 8), 
(2, 9), 
(3, 10), 
(6, 11), 
(1, 12), 
(9, 13),
(6, 14), 
(1, 15), 
(3, 16), 
(5, 17), 
(6, 18), 
(10, 19),
(1, 20),
(2, 21),
(1, 22), 
(1, 23), 
(8, 24), 
(1, 25), 
(6, 26),
(1, 27), 
(6, 28), 
(6, 29),
(9, 30),
(1, 31),
(12, 32),
(6, 33),
(9, 34),
(1, 35),
(8, 36),
(6, 37),
(6, 38),
(7, 39),
(11, 40),
(1, 41),
(10, 42),
(6, 43),
(9, 44),
(11, 45),
(9, 46);

INSERT INTO user_favorites (user_id, destination_id)
VALUES (1, 7), 
(1, 12), 
(1, 37), 
(1, 38), 
(2, 3), 
(2, 9), 
(2, 15), 
(2, 22), 
(3, 2), 
(3, 5),
(3, 28),
(3, 42);