INSERT INTO users (name) 
VALUES ('Joe Bloggs'), 
('John Doe'), 
('Jane Smith');

INSERT INTO provinces (full_name, short_name)
VALUES ('Ontario', 'ON'), 
('Quebec', 'QC'),
('Nova Scotia', 'NS'),
('New Brunswick', 'NB'),
('Manitoba', 'MB'),
('British Columbia', 'BC'),
('Prince Edward Island', 'PE'),
('Saskatchwan', 'SK'),
('Alberta', 'AB'),
('Newfoundland and Labrador', 'NL'), 
('Northwest Territories', 'NT'), 
('Yukon', 'YT'), 
('Nunavut', 'NU');

INSERT INTO destinations (name, wiki_name, google_place_id)
VALUES ('Jasper', 'Jasper, Alberta', 'ChIJKT5VaAgrg1MRgigZC70CIB8'), 
('Banff', 'Banff, Alberta', 'ChIJ_UoMkUXKcFMRY5Ss2r6ur8o'), 
('Vancouver', 'Vancouver', 'ChIJs0-pQ_FzhlQRi_OBm-qWkbs'), 
('Lake Louise', 'Lake Louise, Alberta', 'ChIJEc7hoChdd1MR5rxlY3s8Nzw'), 
('Toronto', 'Toronto', 'ChIJpTvG15DL1IkRd8S0KlBVNTI'), 
('Montreal', 'Montreal', 'ChIJDbdkHFQayUwR7-8fITgxTmU'), 
('Revelstoke', 'Revelstoke, British Columbia', 'ChIJpd1q-gU3eVMRyu_WuX1kPE8'), 
('Haida Gwaii', 'Haida Gwaii', 'ChIJAzMGVmJvbFQR673y7geLkuw'), 
('Quebec City', 'Quebec City', 'ChIJk4jbBYqWuEwRAzro8GMtxY8'), 
('Louisbourg', 'Louisbourg', 'ChIJbSHDjFQdaEsR3aRei1h4IVQ'), 
('Whistler', 'Whistler, British Columbia', 'ChIJh3uVA7I8h1QR9s_1dehBt0o'), 
('Ottawa', 'Ottawa', 'ChIJrxNRX7IFzkwR7RXdMeFRaoo'), 
('Calgary', 'Calgary', 'ChIJ1T-EnwNwcVMROrZStrE7bSY'),
('Victoria', 'Victoria, British Columbia', 'ChIJcWGw3Ytzj1QR7Ui7HnTz6Dg'), 
('Niagara Falls', 'Niagara Falls, Ontario', 'ChIJuU2C7F5E04kRiKK9VmHF0kY'), 
('Halifax', 'Halifax, Nova Scotia', 'ChIJwfrbBxQhWksR3C2LQ6bja2Y'), 
('Winnipeg', 'Winnipeg', 'ChIJESsa-ftz6lIRZMq5xvoaKis'), 
('Kelowna', 'Kelowna', 'ChIJszDH47aMfVMR98S02j3l-E4'), 
('St. John''s', 'St. John''s, Newfoundland and Labrador', 'ChIJYaIKa46jDEsRHyYSHwDUH54'),
('Kingston', 'Kingston, Ontario', 'ChIJqY5AdAar0kwR6tnWFXdJpXY'),
('Mont-Tremblant', 'Mont-Tremblant', 'ChIJF1KUvA12z0wRwFRNrq0MBAU'),
('Hamilton', 'Hamilton, Ontario', 'ChIJj3feJ2yYLIgRIQ7f2Fbuais'), 
('Niagara-on-the-Lake', 'Niagara-on-the-Lake', 'ChIJsQIX2RRf04kRwKIRfVRRAXY'), 
('Saskatoon', 'Saskatoon', 'ChIJK5ntR7_2BFMRkCZ3lTKeBAU'), 
('London', 'London, Ontario', 'ChIJC5uNqA7yLogRlWsFmmnXxyg'), 
('Vancouver Island', 'Vancouver Island', 'ChIJD9RbwiQYiFQRtWoKQiKWmVI'),
('Algonquin Provincial Park', 'Algonquin Provincial Park', 'ChIJ_21BPMh51kwR62D0aOu7bUM'), 
('Nanaimo', 'Nanaimo', 'ChIJWxysIF6hiFQR0A97KhU1AQU'), 
('Kamloops', 'Kamloops', 'ChIJMTsNPdMsflMR50VpmqqWPtI'),
('Jasper National Park Of Canada', 'Jasper National Park', 'ChIJG4dCkcspg1MRktGbzm1KcuE'),
('Mississauga', 'Mississauga', 'ChIJtwVr559GK4gR22ZZ175sFAM'),
('Whitehorse', 'Whitehorse', 'ChIJgVO8gJhEVFERSzXQZOq3PeQ'),
('Big White Ski Resort', 'Big White Ski Resort', 'ChIJNVeBt_-efVMRzAA5aCq3VRY'),
('Canmore', 'Canmore, Alberta', 'ChIJMWNFlZXFcFMRLmkenl8xtkY'),
('Windsor', 'Windsor, Ontario', 'ChIJa4hPtcEqO4gRUdz8J5XUbLY'),
('Regina', 'Regina, Saskatchewan', 'ChIJ6z2l-0AeHFMRsVR7t5YySjU'),
('Yoho National Park Of Canada', 'Yoho National Park', 'ChIJUxBJITveeVMRdW-P2NvpnPI'),
('Squamish', 'Squamish, British Columbia', 'ChIJcy14rBX4hlQR2xFaSWhoqa8'),
('Charlottetown', 'Charlottetown', 'ChIJxYN_1N1SXksRJ5tRn7h3V1o'),
('Yellowknife', 'Yellowknife', 'ChIJyYJGoyzx0VMRge9xQyQ3wbQ'),
('Kitchener', 'Kitchener, Ontario', 'ChIJBVHuA4z0K4gRS1Rf3-b4JZU'),
('Gros Morne National Park Of Canada', 'Gros Morne National Park', 'ChIJ72vPHCBFeUsRdjmRPWNqdWU'),
('Glacier National Park of Canada', 'Glacier National Park (Canada)', 'ChIJxWd-JkUIeVMRuQ7amxSgRPA'),
('Athabasca Glacier', 'Athabasca Glacier', 'ChIJVaomLeX-d1MRZ9IZJSjcXTw'),
('Nahanni National Park Reserve of Canada', 'Nahanni National Park Reserve', 'ChIJybuQCDo94VMRoDoXiK4h0J4'),
('Drumheller', 'Drumheller', 'ChIJHx_0B4ANc1MRWZCRwItZUUw');

INSERT INTO province_destinations (province_id, destination_id)
VALUES (9, 1), 
(9, 2), 
(6, 3), 
(9, 4), 
(1, 5), 
(2, 6), 
(6, 7), 
(6, 8), 
(2, 9), 
(3, 10), 
(6, 11), 
(1, 12), 
(9, 13),
(6, 14), 
(1, 15), 
(3, 16), 
(5, 17), 
(6, 18), 
(10, 19),
(1, 20),
(2, 21),
(1, 22), 
(1, 23), 
(8, 24), 
(1, 25), 
(6, 26),
(1, 27), 
(6, 28), 
(6, 29),
(9, 30),
(1, 31),
(12, 32),
(6, 33),
(9, 34),
(1, 35),
(8, 36),
(6, 37),
(6, 38),
(7, 39),
(11, 40),
(1, 41),
(10, 42),
(6, 43),
(9, 44),
(11, 45),
(9, 46);

INSERT INTO user_favorites (user_id, destination_id)
VALUES (1, 7), 
(1, 12), 
(1, 37), 
(1, 38), 
(2, 3), 
(2, 9), 
(2, 15), 
(2, 22), 
(3, 2), 
(3, 5),
(3, 28),
(3, 42);

INSERT INTO things_to_bring (destination_id, thing)
VALUES (1, '🎒 Waterproof backpack'), 
(1, '📱 Waterproof phone case'), 
(1, '🧭 GPS/compass'), 
(1, '🕶️ Sunglasses'), 
(1, '☔ Raingear'), 
(1, '🥾 Hiking boots'), 
(2, '🎒 Waterproof backpack'), 
(2, '🐻 Bear spray'), 
(2, '🧭 GPS/compass'), 
(2, '🕶️ Sunglasses'), 
(2, '🥾 Hiking boots'), 
(2, '🔋 Extra batteries'), 
(3, '🕶️ Sunglasses'), 
(3, '🏖️ Beach towel'), 
(3, '👟 Walking shoes'), 
(3, '📷 Camera'), 
(3, '🚰 Water bottle'), 
(3, '👕 Sweatshirt'), 
(4, '🧤 Gloves'), 
(4, '🎒 Waterproof backpack'), 
(4, '📱 Waterproof phone case'), 
(4, '🧶 Fleece'), 
(4, '☔ Raingear'), 
(4, '🦟 Insect spray'), 
(5, '👟 Walking shoes'), 
(5, '🧴 Moisturizer'), 
(5, '🔌 Device chargers'), 
(5, '🎧 Ear plugs'), 
(5, '🎫 Toronto CityPass'), 
(5, '👖 Jeans'), 
(6, '👟 Walking boots'), 
(6, '🩲 Thermal base layers'), 
(6, '🧥 Lightweight puffer'), 
(6, '👖 Ski pants'), 
(6, '🔌 Device chargers'), 
(6, '💊 Antacids'), 
(7, '🩲 Thermal underwear'), 
(7, '🥾 Boots'), 
(7, '🧦 Wool socks'), 
(7, '🎿 Skis'), 
(7, '🎩 Toque'), 
(7, '👖 Snow pants'), 
(8, '☔ Raingear'), 
(8, '🧥 Paddle jacket'), 
(8, '📷 Camera'), 
(8, '🩳 Quick drying shorts & pants'), 
(8, '🕶️ Sunglasses'), 
(8, '🔋 Extra batteries'), 
(9, '👕 Nice shirts'), 
(9, '👕 Sweaters'), 
(9, '📕 Journal and pens'), 
(9, '📕 Book'), 
(9, '📞 Phone'), 
(9, '🎧 Headphones'), 
(10, '👟 Walking shoes'), 
(10, '🥾 Hiking boots'), 
(10, '🦟 Insect repellent'), 
(10, '🕶️ Sunglasses'), 
(10, '🚰 Water bottle'), 
(10, '🎧 Earbuds'), 
(11, '💄 Lip balm'), 
(11, '🌞 Sunscreen'), 
(11, '🦟 Bug spray'), 
(11, '🧥 Rainjacket'), 
(11, '🥾 Hiking boots'), 
(11, '👕 Sweaters'), 
(12, '👕 Sweatshirts'), 
(12, '👕 T-shirts'), 
(12, '👟 Walking shoes'), 
(12, '🌞 Sunscreen'), 
(12, '🎒 Waterproof backpack'), 
(12, '📱 Waterproof phone case'), 
(13, '🎧 Ear plugs'), 
(13, '🥽 Eye mask'), 
(13, '🧥 Hard shell jacket'), 
(13, '🧴 Moisturizer'), 
(13, '🧶 Fleece'), 
(13, '🥤 Travel mug'), 
(14, '🥾 All-weather shoes'), 
(14, '🔭 Binoculars'), 
(14, '📷 Camera'), 
(14, '🥪 Picnic blanket'), 
(14, '🧥 Rain jacket'), 
(14, '🌞 Sunscreen'), 
(15, '🩱 Bathing suit'), 
(15, '🥿 Waterproof shoe covers'), 
(15, '📱 Waterproof phone case'), 
(15, '🛍️ Waterproof bag'), 
(15, '🦟 Insect repellent'), 
(15, '🔭 Binoculars'), 
(16, '👟 Walking shoes'), 
(16, '🧥 Waterproof jacket'), 
(16, '🎩 Sun hat'), 
(16, '🌞 Sunscreen'), 
(16, '🩱 Bathing suit'), 
(16, '🏖️ Beach towel'), 
(17, '📕 Books'), 
(17, '🔌 Device chargers'), 
(17, '🧦 Wool socks'), 
(17, '🧥 Wind jacket'), 
(17, '🩹 First Aid Kit'), 
(17, '🍫 Snacks'), 
(18, '🌞 Sunscreen'), 
(18, '🦟 Insect repellent'), 
(18, '🚰 Water bottle'), 
(18, '👕 Long sleeve shirt'), 
(18, '🍫 Snacks'), 
(18, '🎩 Sun hat'), 
(19, '👕 Sweaters'), 
(19, '🧥 Rain jacket'), 
(19, '📷 Camera'), 
(19, '🥾 Hiking shoes'), 
(19, '🗺️ Map'), 
(19, '🛍️ Waterproof bag'), 
(20, '📕 Books'), 
(20, '🔋 Extra batteries'), 
(20, '🎧 Ear plugs'), 
(20, '🧥 Wind jacket'), 
(20, '☔ Raingear'), 
(20, '🩱 Bathing suit'), 
(21, '🎿 Ski gear'), 
(21, '🩲 Quality base layers'), 
(21, '🧦 Wool socks'), 
(21, '🎥 Video camera'), 
(21, '🌞 Sunscreen'), 
(21, '🎩 Toque'), 
(22, '🧶 Fleece'), 
(22, '👖 Jeans'), 
(22, '👟 Sneakers'), 
(22, '🧥 Rain jacket'), 
(22, '🚰 Water bottle'), 
(22, '👜 Day pack'), 
(23, '🧥 Waterproof trench coat'), 
(23, '🧣 Scarf'), 
(23, '🩲 Thermal base layers'), 
(23, '☔ Raingear'), 
(23, '📷 Waterproof camera'), 
(23, '🧣 Quick dry towels'), 
(24, '👟 Walking shoes'), 
(24, '🌞 Sunscreen'), 
(24, '🚰 Water bottle'), 
(24, '🎧 Headphones'), 
(24, '💊 Aspirin'), 
(24, '🩹 First aid kit'), 
(25, '🎩 Hats'), 
(25, '🌞 Sunscreen'), 
(25, '📷 Camera'), 
(25, '👜 Day pack'), 
(25, '👕 Sweatshirts'), 
(25, '🔌 Device chargers'), 
(26, '🧥 Waterproof jacket'), 
(26, '👕 Wool shirts'), 
(26, '🩱 Swimsuits'), 
(26, '☔ Umbrella'), 
(26, '👕 Hoodies'), 
(26, '🦟 Insect spray'), 
(27, '🎒 Backpack'), 
(27, '🧦 Thermal socks'), 
(27, '👕 Long sleeve shirts'), 
(27, '🧥 Windbreaker jacket'), 
(27, '👜 Shoulder bag'), 
(27, '🚰 Water bottle'), 
(28, '🩱 Swimsuits'), 
(28, '🧥 Light jacket'), 
(28, '👕 Long sleeved shirts'), 
(28, '👟 Trainers'), 
(28, '🦟 Insect repellent'), 
(28, '🛍️ Waterproof bag'), 
(29, '🧶 Fleece'), 
(29, '🧣 Scarf'), 
(29, '📕 Books'), 
(29, '👟 Sneakers'), 
(29, '📷 Camera'), 
(29, '👜 Day pack'), 
(30, '🧶 Fleece pants'), 
(30, '🗺️ Topo map'), 
(30, '🩹 First aid kit'), 
(30, '🍜 Food'), 
(30, '🌞 Sunscreen'), 
(30, '🧭 GPS/compass'), 
(31, '👖 Jeans'), 
(31, '☔ Umbrella'), 
(31, '🦟 Insect repellent'), 
(31, '💈 Hair dryer'), 
(31, '🔌 Device charger'), 
(31, '👟 Walking shoes'), 
(32, '👕 Warm shirts & pants'), 
(32, '🩹 First aid kit'), 
(32, '🧤 Gloves'), 
(32, '🎩 Toque'), 
(32, '🌞 Sunscreen'), 
(32, '🧴 Moisturizers'), 
(33, '🎿 Skis'), 
(33, '🧥 Ski jacket & pants'), 
(33, '🎩 Toque'), 
(33, '🧤 Gloves'), 
(33, '🧶 Fleece'), 
(33, '👕 Thermal top & pants'), 
(34, '👖 Waterproof pants'), 
(34, '👕 Long sleeve shirt'), 
(34, '🕶️ Sunglasses'), 
(34, '📞 Phone'), 
(34, '🧴 Moisturizers'), 
(34, '🧦 Wool socks'), 
(35, '👕 Sweatshirts'), 
(35, '☔ Raingear'), 
(35, '👟 Sneakers'), 
(35, '🌞 Sunscreen'), 
(35, '🧥 Windbreaker jacket'), 
(35, '🎧 Headphones'), 
(36, '🥾 Hiking boots'), 
(36, '👕 Sweaters'), 
(36, '🧥 Jacket'), 
(36, '🍫 Snacks'), 
(36, '💄 Lip balm'), 
(36, '🚰 Water bottle'), 
(37, '🥾 Hiking boots'), 
(37, '☔ Raingear'), 
(37, '🐻 Bear spray'), 
(37, '🦟 Insect repellent'), 
(37, '🚰 Water bottle'), 
(37, '🧭 GPS/compass'), 
(38, '🌞 Sunscreen'), 
(38, '🕶️ Sunglasses'), 
(38, '🧥 Light rain jacket'), 
(38, '📷 Camera'), 
(38, '👜 Day pack'), 
(38, '🩹 First aid kit'), 
(39, '🧥 Wind jacket'), 
(39, '🧶 Light fleece jacket'), 
(39, '👟 Walking shoes'), 
(39, '🩱 Bathing suit'), 
(39, '📷 Camera'), 
(39, '🔋 Extra batteries'), 
(40, '🩲 Thermal base layers'), 
(40, '🧶 Fleece sweaters'), 
(40, '🎩 Winterproof hat/toque'), 
(40, '🛰️ Satellite phone'), 
(40, '🧶 Fleece neck gaiter'), 
(40, '🧭 GPS/compass'), 
(41, '👟 Walking shoes'), 
(41, '👕 Long sleeve shirt'), 
(41, '🧥 Waterproof jacket'), 
(41, '👕 Sweaters'), 
(41, '🎧 Headphones'), 
(41, '🎧 Ear plugs'), 
(42, '🎒 Backpack'), 
(42, '🥾 Hiking boots'), 
(42, '🩹 First aid kit'), 
(42, '🧶 Fleece'), 
(42, '👕 Long sleeve shirt'), 
(42, '👖 Wind pants'), 
(43, '🌞 Sunscreen'), 
(43, '🦟 Insect repellent'), 
(43, '🧥 Rain jacket'), 
(43, '🩲 Synthetic layers'), 
(43, '🥾 Hiking boots'), 
(43, '🚰 Water bottles'), 
(44, '🧶 Fleece jacket'), 
(44, '🧣 Scarves'), 
(44, '🎩 Hat'), 
(44, '🩲 Thermal base layers'), 
(44, '🧥 Windbreaker jacket'), 
(44, '🦯 Hiking poles'), 
(45, '🧥 Waterproof jacket & pants'), 
(45, '👢 Rubber boots'), 
(45, '🦟 Insect repellent'), 
(45, '🌞 Sunscreen'), 
(45, '🩲 Long underwear'), 
(45, '👕 Long sleeve shirt'), 
(46, '👜 Day pack'), 
(46, '📕 Books'), 
(46, '🍫 Snacks'), 
(46, '🕶️ Sunglasses'), 
(46, '🚰 Water bottle'), 
(46, '🔌 Device chargers');